@echo off
echo Building PharmGenius application...
echo Checking if node_modules exists...
if not exist node_modules (
    echo Installing dependencies...
    call npm ci
) else (
    echo Dependencies already installed, skipping...
)
echo Starting build...
call npm run build
echo Build completed successfully!
echo.
echo To deploy to Vercel, run:
echo npx vercel
pause