services:
  - type: web
    name: pharmgenius
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: COSMOS_DB_ENDPOINT
        sync: false
      - key: COSMOS_DB_KEY
        sync: false
      - key: COSMOS_DB_DATABASE
        value: pharmgenius
      - key: COSMOS_DB_CONTAINER
        value: drugs