# Render Blueprint for PharmGenius
# Full-stack deployment configuration

services:
  # Backend Service (Node.js/Express)
  - type: web
    name: pharmgenius-backend
    plan: free
    region: oregon
    runtime: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: ""
        sync: false
      - key: JWT_SECRET
        value: ""
        sync: false
      - key: CORS_ORIGIN
        value: ""
        sync: false
      - key: AUTH_DISABLED
        value: "false"
      # - key: LOG_LEVEL
      #   value: info

  # Frontend Service (React)
  - type: web
    name: pharmgenius-frontend
    plan: free
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: "https://pharmgenius-backend.onrender.com"
      - key: VITE_AUTH_DISABLED
        value: "false"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
    env
